### ISSUE TITLE
How this player works?

### ISSUE THREAD

**Issue by antontuz** [brasky/OpenSync#57]
Hey! May you explain to me how this player works? what happens when I insert a link to player?

**Comment by brasky** [comment]
Hi @INTERNALINTERFERENCE, most of the work is done in Sync.razor in the client. 

When you add a video, the first thing we do is call Send()
https://github.com/brasky/OpenSync/blob/master/OpenSync/Client/Pages/Sync.razor#L416

This does a few things, but most importantly it adds the video to a playlist and tells the other clients about the new video by telling the server (also called "Hub") about the new video https://github.com/brasky/OpenSync/blob/master/OpenSync/Client/Pages/Sync.razor#L443

**Comment by INTERNALINTERFERENCE** [comment]
thanks! btw you can check my [version ](https://youtubetogether.azurewebsites.net/) :3
